name: "My Fist GitHub Actions"
on: ["push", "pull_request"]
jobs:
  first_job:
    name: "First Job"
    if: github.event_name == 'push'
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        nodejs: ["14.x", "16.x"]

    runs-on: ${{matrix.os}}
    # window에서 14일때 한 번, 16일 때 한 번 이런식으로 총 6번 돌아간다

    steps:
      - name: Choose node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.nodejs}}

      - name: Say Hello from ${{matrix.os}}
        shell: bash
        run: |
          echo "Hello, from ${{matrix.os}}"
          echo "node version : $(node --version)"

  second_job:
    name: "First Job"
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        nodejs: ["14.x", "16.x"]

    runs-on: ${{matrix.os}}
    # window에서 14일때 한 번, 16일 때 한 번 이런식으로 총 6번 돌아간다

    steps:
      - name: Choose node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.nodejs}}

      - name: Say Hello from ${{matrix.os}}
        shell: bash
        run: |
          echo "Hello, from ${{matrix.os}}"
          echo "node version : $(node --version)"
