name: "My Fist GitHub Actions"
on: ["push", "pull_request"]
jobs:
  first_job:
    name: "First Job"
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello from Frist Job
        shell: bash
        run: |
          echo "Hello World"

  Second_job:
    name: "second Job"
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello from Second Job
        shell: bash
        run: |
          echo "Loem Ipsum"
